apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yellow
  template:
    metadata:
      labels:
        app: yellow
    spec:
      containers:
      - image: okteto.dev/yellow:latest
        name: yellow
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ca8e3b97-4442-4078-bbf0-8f59bc084eae"
        - name: Vless_Path
          value: "/vl5ifty"
        - name: Vmess_UUID
          value: "ca8e3b97-4442-4078-bbf0-8f59bc084eae"
        - name: Vmess_Path
          value: "/vm6ktyu6"
        - name: Share_Path
          value: "/v2link"
